In [1]:
import numpy as np
import matplotlib.pyplot as plt

import csv
import pandas as pd

In [2]:
ls

file_imports.ipynb      pyLIMA-tutorial2.ipynb  raw_data/
out.tbl                 pyLIMA-tutorial4.ipynb  reduced_data/
pyLIMA-tutorial1.ipynb  pyLIMA-tutorial5.ipynb  Untitled.ipynb


In [3]:
cd raw_data

/home/ezequiel/examples/raw_data


# Importing and reducing the ATLAS data (scratch work)

In [4]:
#data =np.loadtxt('atlas_Gaia21bsg.txt',dtype=np.ndarray,usecols=(0,1,2,5))
atlas = np.loadtxt('atlas_Gaia21bsg.txt', dtype=np.ndarray,usecols=(0,1,2,5))
test = np.loadtxt('atlas_Gaia21bsg.txt',usecols=(0,1,2))
#atlas = np.genfromtxt('atlas_Gaia21bsg.txt',dtype=None)

In [5]:
atlas

array([['59311.545862', '18.768', '0.132', 'c'],
       ['59311.563366', '18.553', '0.120', 'c'],
       ['59311.567516', '18.742', '0.144', 'c']], dtype=object)

In [6]:
np.shape(atlas)

(3, 4)

In [7]:
type(atlas)

numpy.ndarray

In [8]:
test

array([[5.93115459e+04, 1.87680000e+01, 1.32000000e-01],
       [5.93115634e+04, 1.85530000e+01, 1.20000000e-01],
       [5.93115675e+04, 1.87420000e+01, 1.44000000e-01]])

In [9]:
type(test)

numpy.ndarray

# Filtering Raw Data

In [109]:
data = np.loadtxt('job540091.txt',dtype=np.ndarray,usecols=(0,1,2,5))

In [110]:
np.shape(data)

(957, 4)

# np.vstack method (a success!)

In [168]:
#c_filter = np.array(())
#o_filter = np.array(())

c_filter = np.array((0,0,0))
o_filter = np.array((0,0,0))

for i in range(len(data)):
    if data[i,3] == 'c':
        c_filter = np.vstack((c_filter,data[i,0:3]))
        #print('this is c')
    if data[i,3] == 'o':
        o_filter = np.vstack((o_filter,data[i,0:3]))
        #print('this is o')

In [169]:
c_filter

array([[0, 0, 0],
       ['59311.545862', '18.768', '0.132'],
       ['59311.563366', '18.553', '0.120'],
       ['59311.567516', '18.742', '0.144'],
       ['59311.575185', '18.574', '0.106'],
       ['59315.560953', '19.349', '0.215'],
       ['59315.562800', '18.927', '0.206'],
       ['59315.565565', '19.461', '0.254'],
       ['59315.571096', '19.553', '0.420'],
       ['59319.569007', '19.526', '0.184'],
       ['59319.572232', '19.655', '0.191'],
       ['59319.574995', '19.813', '0.275'],
       ['59319.582366', '20.335', '0.388'],
       ['59323.555446', '19.506', '0.190'],
       ['59323.557289', '19.874', '0.223'],
       ['59323.560058', '20.263', '0.318'],
       ['59323.565125', '19.914', '0.282'],
       ['59349.527960', '19.201', '0.168'],
       ['59349.530746', '19.242', '0.145'],
       ['59349.563857', '19.139', '0.165'],
       ['59349.570260', '19.449', '0.208'],
       ['59353.518815', '18.203', '0.059'],
       ['59353.522052', '18.379', '0.097'],
       ['59353

In [175]:
c_filter = np.delete(c_filter,(0),axis=0)

In [176]:
c_filter

array([['59311.545862', '18.768', '0.132'],
       ['59311.563366', '18.553', '0.120'],
       ['59311.567516', '18.742', '0.144'],
       ['59311.575185', '18.574', '0.106'],
       ['59315.560953', '19.349', '0.215'],
       ['59315.562800', '18.927', '0.206'],
       ['59315.565565', '19.461', '0.254'],
       ['59315.571096', '19.553', '0.420'],
       ['59319.569007', '19.526', '0.184'],
       ['59319.572232', '19.655', '0.191'],
       ['59319.574995', '19.813', '0.275'],
       ['59319.582366', '20.335', '0.388'],
       ['59323.555446', '19.506', '0.190'],
       ['59323.557289', '19.874', '0.223'],
       ['59323.560058', '20.263', '0.318'],
       ['59323.565125', '19.914', '0.282'],
       ['59349.527960', '19.201', '0.168'],
       ['59349.530746', '19.242', '0.145'],
       ['59349.563857', '19.139', '0.165'],
       ['59349.570260', '19.449', '0.208'],
       ['59353.518815', '18.203', '0.059'],
       ['59353.522052', '18.379', '0.097'],
       ['59353.545838', '18.126'

In [177]:
np.shape(c_filter)

(237, 3)

In [171]:
o_filter

array([[0, 0, 0],
       ['59321.495895', '18.249', '0.118'],
       ['59321.499556', '18.120', '0.118'],
       ...,
       ['60119.912257', '20.665', '1.343'],
       ['60119.915096', '-23.843', '26.667'],
       ['60119.920427', '19.757', '0.787']], dtype=object)

In [178]:
o_filter = np.delete(o_filter,(0),axis=0)

In [179]:
np.shape(o_filter)

(720, 3)

In [183]:
np.savetxt('atlas_c_filter.dat',c_filter,fmt='%s')

In [184]:
np.savetxt('atlas_o_filter.dat',o_filter,fmt='%s')

# Importing and reducing the ZTF data

In [186]:
pwd

'/home/ezequiel/examples/raw_data'

In [187]:
df = pd.read_csv('ztf_rawdata.csv')

In [188]:
np.shape(df)

(14, 23)

In [ ]:
df

# Importing and reducing the LCO (star 20957) data

In [ ]:
df.to_csv('ztf_gaiabsg21_reduced.dat',sep=' ', index = False)

In [ ]:
data1 = pd.read_csv('data/star_20957_Gaia21bsg_fs01_ip.dat', sep='  ')

In [ ]:
np.shape(data1)

In [ ]:
data1

In [ ]:
data1.columns.name = None

In [ ]:
data1

In [ ]:
data1.to_csv('file1.dat',sep = ' ',index=False)

# Importing and reducing the LCO (star 79874) data

In [ ]:
data2 = pd.read_csv('data/star_79874_Gaia21bsg_ip.dat', sep='  ')

In [ ]:
np.shape(data2)

In [ ]:
data2

In [ ]:
del data2["Calibrated mag,"]


In [ ]:
del data2["mag_error,.1"]

In [ ]:
del data2["Corrected mag,"]

In [ ]:
del data2["mag_error,.2"]

In [ ]:
del data2["QC Flag,"]

In [ ]:
del data2["Image"]

In [ ]:
np.shape(data2)

In [ ]:
data2

In [ ]:
data2.to_csv('file2.dat', sep=' ',index=False)

# Importing and reducing the LCO (star 50085) data

In [ ]:
data3 = pd.read_csv('data/star_50085_Gaia21bsg_gp.dat', sep='  ')

In [ ]:
np.shape(data3)

In [ ]:
data3

In [ ]:
del data3["Calibrated mag,"]


In [ ]:
del data3["mag_error,.1"]

In [ ]:
del data3["Corrected mag,"]

In [ ]:
del data3["mag_error,.2"]

In [ ]:
del data3["QC Flag,"]

In [ ]:
del data3["Image"]

In [ ]:
np.shape(data3)

In [ ]:
data3

In [ ]:
data3.to_csv('file3.dat',sep=' ', index=False)

# Break

# Getting rid of negative values in the reduced c and o filter files of atlas

In [4]:
import numpy as np

In [5]:
atlas_c = np.loadtxt('reduced_data/atlas_c_filter.dat')

In [13]:
type(atlas_c)

numpy.ndarray

In [18]:
len(atlas_c)

169

In [27]:
atlas_c[139,1]

20.78

In [28]:
atlas_c[139,0:3]

array([6.01122317e+04, 2.07800000e+01, 9.65000000e-01])

In [15]:
atlas_c[10,1] < 0

False

In [30]:
#c_filter_reduced = np.array((0,0,0))
#o_filter_reduced = np.array((0,0,0))

for i in range(139):
    if atlas_c[i,1] < 0:   # checking to see if mag is negative (do not need)
        atlas_c = np.delete(atlas_c, (i), axis=0)
        #print('yes')

IndexError: index 133 is out of bounds for axis 0 with size 133

In [8]:
import numpy as np
gaia = np.loadtxt('raw_data/gaia_data_errmissing.csv',usecols=(2,3))

ValueError: invalid column index 2 at row 1 with 2 columns

In [5]:
def estimateGaiaError(mag):
    a1=0.2
    b1= -5.3#-5.2
    log_err1 = a1*mag + b1
    a2=0.2625
    b2= -6.3625#-6.2625
    log_err2 = a2*mag + b2    
    
    if (mag<13.5): expectedStdAtBaselineMag = 10**(a1*13.5+b1)
    if (mag>=13.5 and mag<17) : expectedStdAtBaselineMag = 10**log_err1
    if (mag>=17) : expectedStdAtBaselineMag = 10**log_err2
    
    #this works until 21 mag.    
    
    return expectedStdAtBaselineMag

# Converting date to MJD (gaia)

In [2]:
cd raw_data

/home/ezequiel/examples/raw_data


In [3]:
ls

atlas_Gaia21bsg.txt       job540091.txt  ztf_rawdata.csv
gaia_data_errmissing.csv  out.xlsx


In [6]:
import numpy as np
import pandas as pd
gaia = pd.read_csv('gaia_data_errmissing.csv')

In [7]:
gaia

#Date       JD(TCB)  averagemag
0   2015-09-03 17:45:34  2.457269e+06       19.57
1   2016-03-05 12:10:56  2.457453e+06       19.53
2   2016-03-05 16:24:37  2.457453e+06       19.54
3   2016-04-08 09:58:26  2.457487e+06       19.61
4   2016-04-08 11:45:01  2.457487e+06       19.55
..                  ...           ...         ...
56  2022-10-25 00:45:34  2.459878e+06       19.54
57  2023-04-10 17:25:14  2.460045e+06       19.56
58  2023-04-10 19:11:49  2.460045e+06       19.57
59  2023-04-25 07:20:38  2.460060e+06       19.58
60  2023-04-25 11:34:20  2.460060e+06       19.54

[61 rows x 3 columns]

In [39]:
gaia1 = np.loadtxt('gaia_data_errmissing.csv',delimiter=',',dtype=str,usecols=(0))

In [40]:
gaia1

array(['2015-09-03T17:45:34', '2016-03-05T12:10:56',
       '2016-03-05T16:24:37', '2016-04-08T09:58:26',
       '2016-04-08T11:45:01', '2016-04-23T22:07:16',
       '2016-10-30T16:33:39', '2016-10-30T18:20:13',
       '2016-10-30T22:33:52', '2016-10-31T00:20:26',
       '2017-01-28T17:58:16', '2017-01-28T23:58:32',
       '2017-02-07T06:06:19', '2017-02-07T13:53:09',
       '2017-03-16T02:44:54', '2017-08-05T02:08:30',
       '2017-08-20T20:13:45', '2017-08-20T22:00:19',
       '2017-09-24T09:25:16', '2018-02-05T02:24:06',
       '2018-02-05T04:10:41', '2018-03-26T20:09:53',
       '2018-08-14T03:12:45', '2018-08-14T04:59:19',
       '2018-09-05T15:09:23', '2018-10-05T02:47:12',
       '2019-02-14T09:32:05', '2019-02-14T11:18:39',
       '2019-03-10T09:28:56', '2019-08-19T08:16:03',
       '2019-08-19T10:02:36', '2019-09-13T16:53:28',
       '2020-02-20T21:12:05', '2020-03-18T14:33:38',
       '2020-03-18T16:20:13', '2020-04-11T21:28:02',
       '2020-08-14T15:11:21', '2020-08-14T16:5

In [52]:
np.shape(gaia1)

(61,)

In [45]:
from astropy.time import Time

In [46]:
times = gaia1

In [47]:
times

array(['2015-09-03T17:45:34', '2016-03-05T12:10:56',
       '2016-03-05T16:24:37', '2016-04-08T09:58:26',
       '2016-04-08T11:45:01', '2016-04-23T22:07:16',
       '2016-10-30T16:33:39', '2016-10-30T18:20:13',
       '2016-10-30T22:33:52', '2016-10-31T00:20:26',
       '2017-01-28T17:58:16', '2017-01-28T23:58:32',
       '2017-02-07T06:06:19', '2017-02-07T13:53:09',
       '2017-03-16T02:44:54', '2017-08-05T02:08:30',
       '2017-08-20T20:13:45', '2017-08-20T22:00:19',
       '2017-09-24T09:25:16', '2018-02-05T02:24:06',
       '2018-02-05T04:10:41', '2018-03-26T20:09:53',
       '2018-08-14T03:12:45', '2018-08-14T04:59:19',
       '2018-09-05T15:09:23', '2018-10-05T02:47:12',
       '2019-02-14T09:32:05', '2019-02-14T11:18:39',
       '2019-03-10T09:28:56', '2019-08-19T08:16:03',
       '2019-08-19T10:02:36', '2019-09-13T16:53:28',
       '2020-02-20T21:12:05', '2020-03-18T14:33:38',
       '2020-03-18T16:20:13', '2020-04-11T21:28:02',
       '2020-08-14T15:11:21', '2020-08-14T16:5

In [49]:
t = Time(times, format='isot', scale='utc')

In [54]:
mjd = t.mjd

In [51]:
np.shape(t)

(61,)

In [55]:
np.savetxt('mjd_time.csv',mjd,fmt='%s')

# Computing err_mag (gaia)

In [58]:
gaia_err = np.loadtxt('mjd_time.csv',delimiter=',')

In [59]:
gaia_err

array([[5.72687400e+04, 1.95700000e+01],
       [5.74525076e+04, 1.95300000e+01],
       [5.74526838e+04, 1.95400000e+01],
       [5.74864156e+04, 1.96100000e+01],
       [5.74864896e+04, 1.95500000e+01],
       [5.75019217e+04, 1.96100000e+01],
       [5.76916900e+04, 1.95500000e+01],
       [5.76917640e+04, 1.95700000e+01],
       [5.76919402e+04, 1.95800000e+01],
       [5.76920142e+04, 1.96700000e+01],
       [5.77817488e+04, 1.96000000e+01],
       [5.77819990e+04, 1.95700000e+01],
       [5.77912544e+04, 1.96000000e+01],
       [5.77915786e+04, 1.96000000e+01],
       [5.78281145e+04, 1.95200000e+01],
       [5.79700892e+04, 1.95500000e+01],
       [5.79858429e+04, 1.95200000e+01],
       [5.79859169e+04, 1.95700000e+01],
       [5.80203925e+04, 1.95800000e+01],
       [5.81541001e+04, 1.96000000e+01],
       [5.81541741e+04, 1.96200000e+01],
       [5.82038402e+04, 1.95700000e+01],
       [5.83441339e+04, 1.94500000e+01],
       [5.83442079e+04, 1.95600000e+01],
       [5.836663

In [60]:
np.shape(gaia_err)

(61, 2)

In [85]:
mag = gaia_err[:,1]

err = np.array((0))
for i in range(len(mag)):
    err = np.vstack((err,estimateGaiaError(mag[i])))

#mag0 = estimateGaiaError(mag[0])
#print(mag0)

array([[0.        ],
       [0.0595148 ],
       [0.05809316],
       [0.05844535],
       [0.06097124],
       [0.05879969],
       [0.06097124],
       [0.05879969],
       [0.0595148 ],
       [0.05987562],
       [0.06322299],
       [0.06060382],
       [0.0595148 ],
       [0.06060382],
       [0.06060382],
       [0.05774309],
       [0.05879969],
       [0.05774309],
       [0.0595148 ],
       [0.05987562],
       [0.06060382],
       [0.06134088],
       [0.0595148 ],
       [0.05535094],
       [0.05915616],
       [0.05704926],
       [0.05809316],
       [0.06023862],
       [0.05844535],
       [0.05670548],
       [0.05987562],
       [0.05987562],
       [0.05915616],
       [0.05809316],
       [0.05879969],
       [0.05809316],
       [0.05844535],
       [0.05535094],
       [0.05636377],
       [0.05670548],
       [0.04787679],
       [0.04845906],
       [0.04294128],
       [0.01692875],
       [0.01692875],
       [0.04372703],
       [0.04452716],
       [0.046

In [87]:
err = np.delete(err,(0),axis=0)

In [89]:
np.shape(err)

(61, 1)

In [90]:
np.savetxt('gaia_err_mag.csv',err,fmt='%s')

# Converting all mjd data to hjd [atlas (c, o filter), ztf, gaia]

In [208]:
import math

def calc_hjd(mjd_utc,year,debug=False):
    """Function to calculate the Heliocentric Julian Date from the parameters
    in a typical image header:    
    
    :params string dateobs: DATE-OBS, Exposure start time in UTC,
                            %Y-%m-%dT%H:%M:%S format
    :params float exptime:  Exposure time in seconds
    :params string RA:      RA in sexigesimal hours format
    :params string Dec:     Dec in sexigesimal degrees format    
    
    Returns:    
    
    :params float HJD:      HJD
    """    
    # Convert RA, Dec to radians:
    
    # 17:31:01.48   -21:24:04.43 ----> 262.75616   -21.40123
    
    dRA = 262.75616 
    dRA = dRA * 15.0 * math.pi / 180.0
    dDec = -21.40123
    dDec = dDec * math.pi / 180.0
    #if debug:
    #    print('RA '+RA+' -> decimal radians '+str(dRA))
    #    print('Dec '+Dec+' -> decimal radians '+str(dDec))    # Convert the timestamp into a DateTime object:
    #if 'T' in dateobs:
    #    try:
    #        dt = datetime.strptime(dateobs,"%Y-%m-%dT%H:%M:%S.%f")
    #    except ValueError:
    #        dt = datetime.strptime(dateobs,"%Y-%m-%dT%H:%M:%S")
    #else:
    #    try:
    #        dt = datetime.strptime(dateobs,"%Y-%m-%d %H:%M:%S.%f")
    #    except ValueError:
    #        dt = datetime.strptime(dateobs,"%Y-%m-%d %H:%M:%S")    # Convert the exposure time into a TimeDelta object and add half of it
    # to the time to get the exposure mid-point:
    #expt = timedelta(seconds=exptime)    
    
    #dt = dt + expt/2.0    
    
    #if debug:
     #   print('DATE-OBS = '+str(dateobs))
     #   print('Exposure time = '+str(expt))
     #   print('Mid-point of exposure = '+dt.strftime("%Y-%m-%dT%H:%M:%S.%f"))
     #   at = Time(dateobs,format='isot', scale='utc')
     #   aexpt = TimeDelta(exptime,format='sec')
        
     #  adt = at + aexpt/2.0
     #   print('Astropy: mid-point of exposure = '+adt.value)    
    
    # Calculate the MJD (UTC) timestamp:
    #mjd_utc = datetime2mjd_utc(dt)
    #if debug:
    #    print('MJD_UTC = '+str(mjd_utc))
    #    print('Astropy MJD_UTC = '+str(adt.mjd))    
    
    ########################################################################################
    
    # Correct the MJD to TT:   FROM THIS POINT ONWARDS IF GIVEN MJD
    
    # will need to take all MJD and convert to UTC format using astropy
    # dt.year = year from UTC conversion
    
    mjd_tt = mjd_utc2mjd_tt(mjd_utc)
    if debug:
        print('MJD_TT = '+str(mjd_tt))
        
        att = adt.tt
        print('Astropy MJD_TT = '+str(att.mjd))
            
    # Calculating MJD of 1st January that year:
    (mjd_jan1,iexec) = S.sla_cldj(year,1,1)
    if debug:
        print('MJD of Jan 1, '+str(year)+' = '+str(mjd_jan1))
        
        at_jan1 = Time(str(year)+'-01-01T00:00:00.0',format='isot', scale='utc')
        print('Astropy MJD of Jan 1, '+str(year)+' = '+str(at_jan1.mjd))
    
    # Calculating the MJD difference between the DateObs and Jan 1 of the same year:
    tdiff = mjd_tt - mjd_jan1
    if debug:
        print('Time difference from Jan 1 - dateobs, '+\
                str(year)+' = '+str(tdiff))
        
        atdiff = att.mjd - at_jan1.mjd
        print('Astropy time difference = '+str(atdiff))    
    
    # Calculating the RV and time corrections to the Sun:
    (rv,tcorr) = S.sla_ecor(dRA,dDec,year,int(tdiff),(tdiff-int(tdiff)))
    if debug:
        print('Time correction to the Sun = '+str(tcorr))
    
    # Calculating the HJD:
    hjd = mjd_tt + tcorr/86400.0 + 2400000.5
    if debug:
        print('HJD = '+str(hjd))    
    
    return hjd

In [198]:
import pyslalib.slalib as S

def mjd_utc2mjd_tt(mjd_utc, dbg=False):
    '''Converts a MJD in UTC (MJD_UTC) to a MJD in TT (Terrestial Time) which is
    needed for any position/ephemeris-based calculations.
    UTC->TT consists of: UTC->TAI = 10s offset + 24 leapseconds (last one 2009 Jan 1.)
    	    	    	TAI->TT  = 32.184s fixed offset'''
# UTC->TT offset
    tt_utc = S.sla_dtt(mjd_utc)
    if dbg:
        print('TT-UTC(s)='+str(tt_utc))
    
    # Correct MJD to MJD(TT)
    mjd_tt = mjd_utc + (tt_utc/86400.0)
    if dbg:
        print('MJD(TT)  =  '+str(mjd_tt))    
    return mjd_tt

In [199]:
mjd_tt = mjd_utc2mjd_tt(59311.545862)

In [200]:
print(mjd_tt)

59311.54666274074


# ATLAS c-filter: MJD to HJD

In [94]:
pwd

'/home/ezequiel/examples/raw_data'

In [95]:
cd ~

/home/ezequiel


In [96]:
cd pyLIMA-env/pyLIMA/data

/home/ezequiel/pyLIMA-env/pyLIMA/data


In [97]:
ls

atlas_c_filter.dat     star_20957_Gaia21bsg_fs01_ip_reduced.dat
atlas_o_filter.dat     star_50085_Gaia21bsg_gp_reduced.dat
misc/                  star_79874_Gaia21bsg_ip_reduced.dat
reduced_gaia_data.dat  ztf_gaiabsg21_reduced.dat


In [140]:
atlas_c = np.loadtxt('atlas_c_filter.dat')
atlas_c_mjd = atlas_c[:,0]

In [141]:
np.shape(atlas_c)

(132, 3)

# Will need to first convert all MJD back to UTC

In [142]:
atlas_c_mjd

array([59311.545862, 59311.563366, 59311.567516, 59311.575185,
       59315.560953, 59315.5628  , 59315.565565, 59315.571096,
       59319.569007, 59319.572232, 59319.574995, 59319.582366,
       59323.555446, 59323.557289, 59323.560058, 59323.565125,
       59349.52796 , 59349.530746, 59349.563857, 59349.57026 ,
       59353.518815, 59353.522052, 59353.545838, 59353.574225,
       59371.474699, 59371.477528, 59371.512052, 59371.540534,
       59375.414545, 59375.416847, 59375.420075, 59375.426525,
       59376.386151, 59377.380913, 59377.383681, 59377.386445,
       59377.389813, 59378.381052, 59378.393523, 59378.400231,
       59379.380651, 59379.383417, 59379.38618 , 59379.388952,
       59379.40323 , 59379.405071, 59379.440092, 59380.38066 ,
       59380.384385, 59380.393035, 59381.398459, 59381.401221,
       59405.378509, 59409.376492, 59409.407968, 59409.413457,
       59427.37428 , 59427.402805, 59427.41899 , 59428.426568,
       59428.436461, 59428.450991, 59431.334417, 59431.

In [216]:
np.shape(atlas_c_mjd)

(132,)

In [143]:
t = Time(atlas_c_mjd,format='mjd')
atlas_c_utc = t.isot

In [144]:
atlas_c_utc

array(['2021-04-07T13:06:02.477', '2021-04-07T13:31:14.822',
       '2021-04-07T13:37:13.382', '2021-04-07T13:48:15.984',
       '2021-04-11T13:27:46.339', '2021-04-11T13:30:25.920',
       '2021-04-11T13:34:24.816', '2021-04-11T13:42:22.694',
       '2021-04-15T13:39:22.205', '2021-04-15T13:44:00.845',
       '2021-04-15T13:47:59.568', '2021-04-15T13:58:36.422',
       '2021-04-19T13:19:50.534', '2021-04-19T13:22:29.770',
       '2021-04-19T13:26:29.011', '2021-04-19T13:33:46.800',
       '2021-05-15T12:40:15.744', '2021-05-15T12:44:16.454',
       '2021-05-15T13:31:57.245', '2021-05-15T13:41:10.464',
       '2021-05-19T12:27:05.616', '2021-05-19T12:31:45.293',
       '2021-05-19T13:06:00.403', '2021-05-19T13:46:53.040',
       '2021-06-06T11:23:33.994', '2021-06-06T11:27:38.419',
       '2021-06-06T12:17:21.293', '2021-06-06T12:58:22.138',
       '2021-06-10T09:56:56.688', '2021-06-10T10:00:15.581',
       '2021-06-10T10:04:54.480', '2021-06-10T10:14:11.760',
       '2021-06-11T09:16

In [174]:
test = atlas_c_utc[0][0:4]

In [175]:
int(test)

2021

In [185]:
atlas_c_year = np.array((0))   # extracting the year from the UTC format --> goes into computing the HJD for ATLAS c

for i in range(len(atlas_c_utc)):
    atlas_c_year = np.vstack((atlas_c_year,int(atlas_c_utc[i][0:4])))
    
atlas_c_year = np.delete(atlas_c_year,(0),axis=0)

In [186]:
atlas_c_year

array([[2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [20

In [183]:
int(atlas_c_year[0])

/tmp/ipykernel_20543/3905970950.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  int(atlas_c_year[0])


2021

In [128]:
atlas_o = np.loadtxt('atlas_o_filter.dat')
atlas_o_mjd = atlas_o[:,0]

In [147]:
np.shape(atlas_o)

(570, 3)

In [130]:
t = Time(atlas_o_mjd,format='mjd')
atlas_o_utc = t.isot

In [138]:
np.shape(atlas_o_utc)

(570,)

In [217]:
atlas_o_year = np.array((0))   # extracting the year from the UTC format --> goes into computing the HJD for ATLAS o

for i in range(len(atlas_o_utc)):
    atlas_o_year = np.vstack((atlas_o_year,int(atlas_o_utc[i][0:4])))
    
atlas_o_year = np.delete(atlas_o_year,(0),axis=0)

In [219]:
np.shape(atlas_o_year)

(570, 1)

In [150]:
gaia = np.loadtxt('reduced_gaia_data.dat',delimiter=',')
gaia_mjd = gaia[:,0]

In [151]:
t = Time(gaia_mjd,format='mjd',scale='tcb')
gaia_utc = t.isot

In [152]:
np.shape(gaia_utc)

(61,)

In [224]:
gaia_year = np.array((0))   # extracting the year from the UTC format --> goes into computing the HJD for Gaia

for i in range(len(gaia_utc)):
    gaia_year = np.vstack((gaia_year,int(gaia_utc[i][0:4])))
    
gaia_year = np.delete(gaia_year,(0),axis=0)

In [225]:
gaia_year

array([[2015],
       [2016],
       [2016],
       [2016],
       [2016],
       [2016],
       [2016],
       [2016],
       [2016],
       [2016],
       [2017],
       [2017],
       [2017],
       [2017],
       [2017],
       [2017],
       [2017],
       [2017],
       [2017],
       [2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2020],
       [2020],
       [2020],
       [2020],
       [2020],
       [2020],
       [2020],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2021],
       [2022],
       [2022],
       [2022],
       [2022],
       [2022],
       [2022],
       [2022],
       [2022],
       [2022],
       [2023],
       [2023],
       [2023],
       [2023]])

In [226]:
np.shape(gaia_year)

(61, 1)

In [154]:
ztf = np.loadtxt('ztf_gaiabsg21_reduced.dat')
ztf_mjd = ztf[:,0]

In [157]:
np.shape(ztf)

(355, 3)

In [156]:
t = Time(ztf_mjd,format='mjd')
ztf_utc = t.isot   # UTC conversion

In [158]:
np.shape(ztf_utc)

(355,)

In [231]:
ztf_year = np.array((0))

for i in range(len(ztf_utc)):
    ztf_year = np.vstack((ztf_year,int(ztf_utc[i][0:4])))
    
ztf_year = np.delete(ztf_year,(0),axis=0)

In [232]:
ztf_year

array([[2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2018],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [2019],
       [20

In [233]:
np.shape(ztf_year)

(355, 1)

In [243]:
atlas_c_hjd = np.array((0))
year = atlas_c_utc

for i in range(len(atlas_c)):
    atlas_c_hjd = np.vstack((atlas_c_hjd,calc_hjd(atlas_c_mjd[i],atlas_c_year[i])))   # mjd, year from UTC conversion
    
atlas_c_hjd = np.delete(atlas_c_hjd,(0),axis=0)

/tmp/ipykernel_20543/1167667464.py:74: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (mjd_jan1,iexec) = S.sla_cldj(year,1,1)
/tmp/ipykernel_20543/1167667464.py:91: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (rv,tcorr) = S.sla_ecor(dRA,dDec,year,int(tdiff),(tdiff-int(tdiff)))


In [244]:
atlas_c_hjd

array([[2459312.04249116],
       [2459312.05999628],
       [2459312.06414655],
       [2459312.07181604],
       [2459316.05784911],
       [2459316.05969624],
       [2459316.06246143],
       [2459316.06799281],
       [2459320.06618818],
       [2459320.06941341],
       [2459320.07217662],
       [2459320.07954816],
       [2459324.05292766],
       [2459324.0547708 ],
       [2459324.05754002],
       [2459324.06260741],
       [2459350.02770518],
       [2459350.03049144],
       [2459350.06360555],
       [2459350.07000916],
       [2459354.01893784],
       [2459354.02217514],
       [2459354.04596341],
       [2459354.07435311],
       [2459371.97653342],
       [2459371.97936268],
       [2459372.01388993],
       [2459372.04237462],
       [2459375.91674795],
       [2459375.91905017],
       [2459375.92227847],
       [2459375.92872907],
       [2459376.88844396],
       [2459377.8832977 ],
       [2459377.88606595],
       [2459377.88883021],
       [2459377.89219852],
 

In [245]:
np.shape(atlas_hjd)

(132, 1)

In [246]:
np.savetxt('atlas_c_hjd.csv',atlas_c_hjd,fmt='%s')

# Success for Atlas c-filter!

In [221]:
atlas_o_hjd = np.array((0))

year = atlas_o_utc

for i in range(len(atlas_o)):
    atlas_o_hjd = np.vstack((atlas_o_hjd,calc_hjd(atlas_o_mjd[i],atlas_o_year[i])))
    
atlas_o_hjd = np.delete(atlas_o_hjd,(0),axis=0)

/tmp/ipykernel_20543/1167667464.py:74: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (mjd_jan1,iexec) = S.sla_cldj(year,1,1)
/tmp/ipykernel_20543/1167667464.py:91: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (rv,tcorr) = S.sla_ecor(dRA,dDec,year,int(tdiff),(tdiff-int(tdiff)))


In [222]:
atlas_o_hjd

array([[2459321.9932194 ],
       [2459321.99688068],
       [2459322.01427899],
       [2459322.02120251],
       [2459327.99139958],
       [2459327.99878718],
       [2459328.00616877],
       [2459328.00940104],
       [2459331.96637002],
       [2459331.96821318],
       [2459331.97098041],
       [2459331.97728194],
       [2459338.05657339],
       [2459338.05977267],
       [2459338.06527516],
       [2459338.10014724],
       [2459343.99282483],
       [2459343.99512504],
       [2459343.9978873 ],
       [2459344.0034178 ],
       [2459347.95525085],
       [2459347.95709302],
       [2459347.95985628],
       [2459347.96492875],
       [2459351.97672212],
       [2459351.97856629],
       [2459351.98133155],
       [2459351.98963634],
       [2459356.06070729],
       [2459356.06439165],
       [2459356.07038922],
       [2459356.08053719],
       [2459357.92410124],
       [2459357.92824263],
       [2459357.93965572],
       [2459357.94656738],
       [2459357.95371807],
 

In [241]:
np.savetxt('atlas_o_hjd.csv',atlas_o_hjd,fmt='%s')

# Success for Atlas o-filter!

In [227]:
gaia_hjd = np.array((0))

year = gaia_utc

for i in range(len(gaia)):
    gaia_hjd = np.vstack((gaia_hjd,calc_hjd(gaia_mjd[i],gaia_year[i])))
    
gaia_hjd = np.delete(gaia_hjd,(0),axis=0)

/tmp/ipykernel_20543/1167667464.py:74: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (mjd_jan1,iexec) = S.sla_cldj(year,1,1)
/tmp/ipykernel_20543/1167667464.py:91: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (rv,tcorr) = S.sla_ecor(dRA,dDec,year,int(tdiff),(tdiff-int(tdiff)))


In [228]:
gaia_hjd

array([[2457269.24643064],
       [2457453.00287007],
       [2457453.17904174],
       [2457486.91226615],
       [2457486.9862872 ],
       [2457502.41954669],
       [2457692.19344684],
       [2457692.26744503],
       [2457692.44357551],
       [2457692.51757369],
       [2457782.24463266],
       [2457782.49480669],
       [2457791.74986902],
       [2457792.07404934],
       [2457828.6100486 ],
       [2457970.59531442],
       [2457986.34933884],
       [2457986.42334432],
       [2458020.89843546],
       [2458154.59562769],
       [2458154.66964142],
       [2458204.33615235],
       [2458344.64019215],
       [2458344.71419845],
       [2458367.13795573],
       [2458396.62146296],
       [2458528.89260229],
       [2458528.96660555],
       [2458552.89045907],
       [2458714.85090977],
       [2458714.92490391],
       [2458740.21007795],
       [2458900.3786308 ],
       [2458927.10231908],
       [2458927.17633798],
       [2458951.39140372],
       [2459076.13924199],
 

In [229]:
np.shape(gaia_hjd)

(61, 1)

In [238]:
np.savetxt('gaia_hjd.csv',gaia_hjd,fmt='%s')

# Success for Gaia !

In [235]:
ztf_hjd = np.array((0))

year = ztf_utc

for i in range(len(ztf)):
    ztf_hjd = np.vstack((ztf_hjd,calc_hjd(ztf_mjd[i],ztf_year[i])))

ztf_hjd = np.delete(ztf_hjd,(0),axis=0)

/tmp/ipykernel_20543/1167667464.py:74: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (mjd_jan1,iexec) = S.sla_cldj(year,1,1)
/tmp/ipykernel_20543/1167667464.py:91: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  (rv,tcorr) = S.sla_ecor(dRA,dDec,year,int(tdiff),(tdiff-int(tdiff)))


In [236]:
ztf_hjd

array([[2458246.91617842],
       [2458247.9375564 ],
       [2458256.98046109],
       [2458273.89122958],
       [2458284.81587973],
       [2458336.71510262],
       [2458338.69562008],
       [2458348.70444927],
       [2458593.93608654],
       [2458607.98035119],
       [2458608.97979205],
       [2458636.83591882],
       [2458636.83637027],
       [2458636.83682161],
       [2458636.83727305],
       [2458636.8377245 ],
       [2458636.83817594],
       [2458636.83862738],
       [2458636.83907883],
       [2458636.83953027],
       [2458636.83998171],
       [2458636.84043315],
       [2458636.8408845 ],
       [2458636.84133594],
       [2458636.84178738],
       [2458636.84222722],
       [2458636.84269027],
       [2458636.84314171],
       [2458636.84359316],
       [2458636.8440446 ],
       [2458636.84449604],
       [2458636.84493588],
       [2458636.84538732],
       [2458636.84585027],
       [2458636.84629011],
       [2458636.84675316],
       [2458636.8472046 ],
 

In [237]:
np.shape(ztf_hjd)

(355, 1)

In [239]:
np.savetxt('ztf_hjd.csv',ztf_hjd,fmt='%s')

# Success for ZTF !

# Success! for one single element